### ISSUE TITLE
Q-CTRL Driven control example

### ISSUE THREAD

**Issue by newsma** [qctrl/python-open-controls#3]
I'm trying to run the driven control example, but running into `ImportError: cannot import name 'new_predefined_driven_control' from 'qctrlopencontrols' (/Users/...../miniconda3/lib/python3.7/site-packages/qctrlopencontrols/__init__.py)`  and `cannot import name 'DrivenControl' from 'qctrlopencontrols' (/Users/...../miniconda3/lib/python3.7/site-packages/qctrlopencontrols/__init__.py)`. Any ideas why this is the case? I can successfully import the dds files though.

**Comment by michaelhush** [comment]
The version on PyPI (pip) was behind. That has just been updated. If you installed with pip, try installing the latest version of qctrl-open-controls. That should fix the problem.

If you always want the absolute latest features in the packages I'd suggest considering installing from source using `python setup.py develop`.

Let us know if that fixes the problem.

**Comment by newsma** [comment]
Yes, it does fix the issue. Thank you!!
