### ISSUE TITLE
README jupyter notebook link broken

### ISSUE THREAD

**Issue by drewrisinger** [qctrl/python-open-controls#70]
**Describe the bug**
The top-level README's link to example jupyter notebooks is broken.

**To reproduce**

1. Go to https://github.com/qctrl/python-open-controls#usage
2. Click the *Jupyter notebooks* link.

**Comment by charmasaur** [comment]
Hi Drew,

Thanks for the report! We recently made some changes to how all the Q-CTRL documentation is organised, and this slipped through the cracks. I'll work on migrating the appropriate content into this repo right away, but in the meantime you can see some example usage of the package (being used together with other Q-CTRL tools) at [docs.q-ctrl.com](https://docs.q-ctrl.com).

In particular, take a look at the [filter functions feature guide](https://docs.q-ctrl.com/boulder-opal/feature-guides/notebook?nb=filter-functions), which sets up several different driven controls from this package. You may also find the [cold ions technology guide](https://docs.q-ctrl.com/boulder-opal/technology-guides/notebook?nb=cold-ions-improving-the-performance-of-single-qubit-gates) interesting&mdash;even though it only uses this package to generate a primitive control, the applications to ions may be relevant.

Harry
