### ISSUE TITLE
Disallow negative Rabi rates in DynamicDecouplingSequence

### ISSUE THREAD

**Issue by charmasaur** [qctrl/python-open-controls#90]
At the moment `DynamicDecouplingSequence` accepts negative values for `rabi_rotations`, which is both unnecessary (the same effect could be achieved by adding `pi` to the corresponding `azimuthal_angles` values) and can cause issues later when we try to create a `DrivenControl` (see https://github.com/qctrl/python-open-controls/blob/master/qctrlopencontrols/dynamic_decoupling_sequences/driven_controls.py#L197).

I think it makes sense to disallow negative Rabi rates everywhere rather than allow them everywhere, because then there's less ambiguity about how a certain pulse should be represented.

This task is to update the `DynamicalDecouplingSequence` class to explicitly disallow negative Rabi rates, and to make sure that we're never trying to set negative Rabi rates when creating the predefined sequences here: https://github.com/qctrl/python-open-controls/blob/master/qctrlopencontrols/dynamic_decoupling_sequences/predefined.py.

As part of this, it might make sense to introduce a shared set of validation functions (e.g. in `utils.py`) to check that a given set of Rabi rates, azimuthal angles and detunings are all valid. Those validations can then be used everywhere.

**Comment by tachikoma-li** [comment]
Update: There is now a function called `check_arguments`  in `utils.py` for this task.
