### ISSUE TITLE
Implement predefined DRAG driven control

### ISSUE THREAD

**Issue by charmasaur** [qctrl/python-open-controls#91]
DRAG is a popular pulse in quantum control, so it would be nice to provide a predefined driven control that implements one.

This task is to learn a bit about DRAG and figure out which parameters a user needs to provide in order to create one (I guess there'll need to be a duration, a rotation angle, maybe a segment count (controlling the granularity of the piecewise-constant approximation to the ideal smooth pulse), and maybe some other parameters too -- honestly I don't know that much about DRAG), then implement a predefined driven control.

See https://arxiv.org/pdf/1809.04919.pdf for an overview of DRAG, and https://github.com/qctrl/python-open-controls/blob/master/qctrlopencontrols/driven_controls/predefined.py for the other predefined driven controls.

**Comment by perjlieb** [comment]
@charmasaur for the CR simulation I have defined the following Drag pulse (currently Eq. 2.24 in https://www.overleaf.com/project/5f032b7b9ad54c000126e4e0) and implemented here https://drive.google.com/file/d/1StvzP_EbYAPL7egDRHJ-qKPE0MSZf0bi/view?usp=sharing . Besides the parameters for the Gaussian there is one additional parameter required, often referred to as the Drag parameter as it scales the derivative of the Gaussian. You often find the term half-Drag for setting this parameter to 0.5. Furthermore, there is an implementation in https://github.com/qctrl/numerical-package/tree/master/qctrl_numpy/qutrit, but it looks a bit suspicious and lacks some documentation.

**Comment by tachikoma-li** [comment]
Closed now as it's implemented in #183
