### ISSUE TITLE
Implement predefined Gaussian driven control

### ISSUE THREAD

**Issue by charmasaur** [qctrl/python-open-controls#92]
Gaussian pulses are popular in quantum control, since they have a constrained bandwidth (which helps mitigate the effect of leakage).

This task is to implement a predefined Gaussian driven control. I imagine the parameters we'll need are duration, total Rabi rotation (which will determine the scaling of the Gaussian), number of segments (controlling the piecewise-constant approximation of the ideal smooth Gaussian), and width (giving the standard deviation of the Gaussian). The output should be a DrivenControl describing a piecewise-constant Gaussian envelope centered in the middle of the provided duration, with the specified width, and with amplitude chosen so that the integral of the pulse equals the specified Rabi rotation.

See https://github.com/qctrl/python-open-controls/blob/master/qctrlopencontrols/driven_controls/predefined.py for the other predefined driven controls.

**Comment by charmasaur** [comment]
Here's the paper introducing DRAG, which also has a bit of a discussion about Gaussian pulses: https://arxiv.org/pdf/0901.0534.pdf

**Comment by tachikoma-li** [comment]
Closed as implemented in #182.
