### ISSUE TITLE
Replace `new_predefined_*` functions with per-scheme functions

### ISSUE THREAD

**Issue by charmasaur** [qctrl/python-open-controls#93]
The approach used in `new_predefined_driven_control` and `new_predefined_dds` is somewhat error prone (it's easy for a user to provide an incorrect string) and hard to document (because different parameters are relevant for different schemes).

Replacing the strings with enums would avoid the first problem, but wouldn't help with the second.

Instead we could just replace them with separate functions for each scheme: `new_ramsey_dds`, `new_cpmg_dds`, and so on.

**Comment by tachikoma-li** [comment]
`**kwargs` parameter in the current implementation of `new_predefined_dds` is a bit confusing for users and hard to document. With these new separated functions, I guess we can just remove it and also add type hints. @charmasaur

**Comment by tachikoma-li** [comment]
Maybe we can close this one now?
